message = '    favorite language is python    '
print(message)
print(message.rstrip())
print(message)
print(message.lstrip())
print(message)
print(message.strip())
print(message)
message = message.strip()
print(message)